coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # overall project coverage status
        target: auto       # require coverage >= base commit coverage
        threshold: 0%      # no allowed drop
        informational: false

    patch:
      default:
        # coverage for only changed lines in PRs
        target: auto
        threshold: 0%
        informational: false
